// <auto-generated />
using System;
using BudgetHelper.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetHelper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BudgetHelper.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comunal Expenses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Outoors and Fun"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeId")
                        .IsUnique();

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Internet and TV"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.Expense", b =>
                {
                    b.HasOne("BudgetHelper.Core.Entities.ExpenseType", "Type")
                        .WithOne("Expense")
                        .HasForeignKey("BudgetHelper.Core.Entities.Expense", "TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.ExpenseType", b =>
                {
                    b.HasOne("BudgetHelper.Core.Entities.Category", "Category")
                        .WithMany("Types")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.Category", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("BudgetHelper.Core.Entities.ExpenseType", b =>
                {
                    b.Navigation("Expense")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
